[workspace]
members = [
    "bootloader",
    "kernel",
]
# Userspace is excluded because it uses a different target (x86_64-unknown-none)
exclude = [
    "userspace",
]
resolver = "2"

[profile.release]
panic = "abort"
lto = true
opt-level = 3
